"""
Core module for RAG Studio
"""
from .config.settings import (
    DATABASE_PATH,
    UPLOAD_DIR,
    OUTPUT_DIR,
    DEFAULT_OCR_PROVIDER,
    DEFAULT_LLM_PROVIDER,
    DEFAULT_EMBEDDING_PROVIDER,
    DEFAULT_VECTOR_INDEX_PROVIDER,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_CHUNK_OVERLAP
)

__all__ = [
    "DATABASE_PATH",
    "UPLOAD_DIR",
    "OUTPUT_DIR",
    "DEFAULT_OCR_PROVIDER",
    "DEFAULT_LLM_PROVIDER",
    "DEFAULT_EMBEDDING_PROVIDER",
    "DEFAULT_VECTOR_INDEX_PROVIDER",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_CHUNK_OVERLAP"
]
